// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using knowledge_hub.WebAPI.Database;

#nullable disable

namespace knowledge_hub.WebAPI.Migrations
{
    [DbContext(typeof(databaseContext))]
    [Migration("20220611163027_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceDigital")
                        .HasColumnType("float");

                    b.Property<double>("PricePhysical")
                        .HasColumnType("float");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "J. R. R. Tolkien",
                            CategoryId = 6,
                            Description = "Continuing the story begun in The Hobbit, this is the first part of Tolkien's epic masterpiece, The Lord of the Rings, featuring a striking black cover based on Tolkien's own design, the definitive text, and a detailed map of Middle-earth. Sauron, the Dark Lord, has gathered to him all the Rings of Power - the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring - the ring that rules them all - which has fallen into the hands of the hobbit, Bilbo Baggins. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose. Now published again in B format, J.R.R. Tolkien's great work of imaginative fiction has been labelled both a heroic romance and a classic fantasy fiction. By turns comic and homely, epic and diabolic, the narrative moves through countless changes of scene and character in an imaginary world which is totally convincing in its detail.",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "The Fellowship of the Ring : The Lord of the Rings, Part 1",
                            PriceDigital = 8.9900000000000002,
                            PricePhysical = 14.5,
                            Score = 4.3799999999999999
                        },
                        new
                        {
                            BookId = 2,
                            Author = "J. R. R. Tolkien",
                            CategoryId = 6,
                            Description = "Building on the story begun in The Hobbit, this is the second part of Tolkien's epic masterpiece, The Lord of the Rings, featuring a striking black cover based on Tolkien's own design, the definitive text, and a detailed map of Middle-earth.",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "The Two Towers",
                            PriceDigital = 7.9900000000000002,
                            PricePhysical = 13.5,
                            Score = 4.46
                        },
                        new
                        {
                            BookId = 3,
                            Author = "J. R. R. Tolkien",
                            CategoryId = 6,
                            Description = "Concluding the story begun in The Hobbit, this is the final part of Tolkien's epic masterpiece, The Lord of the Rings. Featuring a striking black cover based on Tolkien's own design, the definitive text, and a detailed map of Middle-earth.",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "The Return of the King",
                            PriceDigital = 7.9900000000000002,
                            PricePhysical = 14.5,
                            Score = 4.5499999999999998
                        },
                        new
                        {
                            BookId = 4,
                            Author = "J. R. R. Tolkien",
                            CategoryId = 6,
                            Description = "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely travelling further than the pantry of his hobbit-hole in Bag End. But his contentment is disturbed when the wizard, Gandalf, and a company of thirteen dwarves arrive on his doorstep one day to whisk him away on an unexpected journey 'there and back again'. They have a plot to raid the treasure hoard of Smaug the Magnificent, a large and very dangerous dragon...",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "The Hobbit",
                            PriceDigital = 6.9900000000000002,
                            PricePhysical = 11.5,
                            Score = 4.2800000000000002
                        },
                        new
                        {
                            BookId = 5,
                            Author = " Hajime Isayama ",
                            CategoryId = 12,
                            Description = "Several hundred years ago, humans were nearly exterminated by giants. Giants are typically several stories tall, seem to have no intelligence and who devour human beings. A small percentage of humanity survied barricading themselves in a city protected by walls even taller than the biggest of giants. Flash forward to the present and the city has not seen a giant in over 100 years - before teenager Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a super-giant that appears from nowhere.",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "Attack On Titan 1",
                            PriceDigital = 5.9900000000000002,
                            PricePhysical = 12.0,
                            Score = 4.4699999999999998
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Chip Zdarsky, Mark Bagley",
                            CategoryId = 9,
                            Description = "In 1962's Amazing Fantasy #15, fifteen-year-old Peter Parker was bitten by a radioactive spider and became the Amazing Spider-Man! 57 years have passed in the real world since that event - so what would have happened if the same amount of time passed for Peter as well? To celebrate Marvel's 80th anniversary, Chip Zdarsky and Spider-Man legend Mark Bagley unite to spin a unique Spidey tale - telling an entire history of Spider-Man from beginning to end, set against the key events of the decades through which he lived!",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "Spider-man: Life Story",
                            PriceDigital = 12.99,
                            PricePhysical = 24.5,
                            Score = 4.21
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Louise Pickford",
                            CategoryId = 8,
                            Description = "Fresh, tasty and bursting with nutritious ingredients and lively aromas, delicious one-bowl, Asian-inspired noodle dishes have never been more popular. Their variety and versatility, speedy cooking time and ability to soak up the bold flavours they're prepared with, make noodle dishes an exotic yet accessible dish and, with The Noodle Bowl, you'll be able to celebrate this wonderful food and feast on the results. ",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "The Noodle Bowl : Over 70 Recipes for Asian-Inspired Noodle Dishes",
                            PriceDigital = 11.99,
                            PricePhysical = 21.5,
                            Score = 4.5
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Louise Pickford",
                            CategoryId = 8,
                            Description = "These hearty one-pot meals, flavoured with fragrant spices, are cooked and served from an elegant, specially designed cooking vessel, also called a tagine. In Ghillie Basan's collection of deliciously authentic recipes you will find some of the best-loved classics of the Moroccan kitchen.",
                            ImagePath = "",
                            LanguageId = 1,
                            Name = "The Modern Tagine Cookbook : Delicious Recipes for Moroccan One-Pot Meals",
                            PriceDigital = 12.6,
                            PricePhysical = 23.5,
                            Score = 3.75
                        });
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.BookUserWishlist", b =>
                {
                    b.Property<int>("BookUserWishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookUserWishlistId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookUserWishlistId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Whishlist");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.CardInfo", b =>
                {
                    b.Property<int>("CardInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardInfoId"), 1L, 1);

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CardInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Art & Photography"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Biography"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Children's Books"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Crafts & Hobbies"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Crime & Thriller"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Ficition"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Food & Drinks"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Graphics Novels"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Manga"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Mind, Body & Spirit"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Science Fiction"
                        });
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            Name = "English"
                        },
                        new
                        {
                            LanguageId = 2,
                            Name = "Deutsch"
                        },
                        new
                        {
                            LanguageId = 3,
                            Name = "Español"
                        },
                        new
                        {
                            LanguageId = 4,
                            Name = "Français"
                        },
                        new
                        {
                            LanguageId = 5,
                            Name = "官話/官话 "
                        },
                        new
                        {
                            LanguageId = 6,
                            Name = "日本語 "
                        });
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("BookId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Name = "User"
                        },
                        new
                        {
                            RoleID = 3,
                            Name = "Delivery"
                        });
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int>("CardInfoId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("CardInfoId");

                    b.HasIndex("OrderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.UserRoles", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleID"), 1L, 1);

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Book", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_hub.WebAPI.Database.Language", "language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("language");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.BookUserWishlist", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_hub.WebAPI.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.CardInfo", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Login", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.User", "User")
                        .WithOne("Login")
                        .HasForeignKey("knowledge_hub.WebAPI.Database.Login", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Order", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_hub.WebAPI.Database.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_hub.WebAPI.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Review", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.Book", "book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_hub.WebAPI.Database.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");

                    b.Navigation("user");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Transaction", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_hub.WebAPI.Database.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.UserRoles", b =>
                {
                    b.HasOne("knowledge_hub.WebAPI.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_hub.WebAPI.Database.User", "User")
                        .WithOne("UserRole")
                        .HasForeignKey("knowledge_hub.WebAPI.Database.UserRoles", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("knowledge_hub.WebAPI.Database.User", b =>
                {
                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("UserRole")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
