version: '3'
services:
  knowledge-hub-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Saber1337aaa
      - MSSQL_PID=Developer
    ports:
      - 1433
    expose:
      - 1433
    networks:
      - knowledge-hub-net

  knowledge-hub-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:knowledge-hub=Server=knowledge-hub-sql,1433;Database=knowledgeHubDB;User=sa;Password=Saber1337aaa;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:5000
    networks:
      - knowledge-hub-net
    links:
      - knowledge-hub-sql
    depends_on:
      - knowledge-hub-sql

networks:
  knowledge-hub-net:
    driver: bridge